"""Generate the 12 px UI glyph subset from a local Chinese TrueType font."""
from pathlib import Path
import argparse
import re
from PIL import Image, ImageDraw, ImageFont

parser = argparse.ArgumentParser()
parser.add_argument("--font", default="C:/Windows/Fonts/msyh.ttc")
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
source = (root / "ui_v2.cpp").read_text(encoding="utf-8")
# Only UI string literals, excluding comments.
strings = re.findall(r'"([^"\n]*)"', source)
characters = sorted({c for s in strings for c in s if '\u4e00' <= c <= '\u9fff'})
font = ImageFont.truetype(args.font, 12)
lines = ["// Generated by tools/generate_chinese_font.py; 12x12 monochrome glyphs.",
         "#pragma once", "#include <stdint.h>",
         "struct ChineseGlyph { uint16_t code; uint16_t rows[12]; };",
         "static const ChineseGlyph chineseGlyphs[] = {"]
preview = Image.new("RGB", (12 * 16, 18 * ((len(characters) + 15) // 16)), "#101820")
for index, character in enumerate(characters):
    glyph = Image.new("L", (12, 12))
    draw = ImageDraw.Draw(glyph)
    bounds = font.getbbox(character)
    draw.text(((12 - (bounds[2] - bounds[0])) // 2 - bounds[0],
               (12 - (bounds[3] - bounds[1])) // 2 - bounds[1]), character, font=font, fill=255)
    rows = [sum((1 << (11 - x)) for x in range(12) if glyph.getpixel((x, y)) >= 100)
            for y in range(12)]
    assert any(rows), character
    lines.append("    {0x%04X, {%s}}, // %s" % (ord(character), ", ".join("0x%03X" % r for r in rows), character))
    tile = Image.new("RGB", (12, 12), "#101820")
    tile.paste("white", mask=glyph.point(lambda p: 255 if p >= 100 else 0))
    preview.paste(tile, ((index % 16) * 12, (index // 16) * 18))
lines.append("};")
(root / "ui_chinese_font.h").write_text("\n".join(lines) + "\n", encoding="utf-8")
preview.resize((preview.width * 4, preview.height * 4), Image.Resampling.NEAREST).save(root / "tools/chinese-font-preview.png")
print(f"Generated {len(characters)} glyphs, {len(characters) * 26} bytes")
